### ISSUE TITLE
Google webfonts niet gebruiken i.v.m. privacy

### ISSUE THREAD

**Issue by milovanderlinden** [codefornl/consul#9]
Sommige maatwerk-configuraties van gemeenten gebruiken Google Webfonts. Dit kan effecten hebben op de privacy van gebruikers

_bron: [stackexchange (engels)](https://webmasters.stackexchange.com/questions/60464/are-there-privacy-considerations-in-using-google-web-fonts)_

Het lijkt mij goed om deze te vervangen waar mogelijk en te overleggen met gemeenten of ze dit wel of niet willen.

**Comment by raoulkramer** [comment]
webfonts er uithalen voor nu?

**Comment by milovanderlinden** [comment]
Niet meer relevant
